<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exploring the Climate-Wine Relationship in Oregon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0073a120dedc1faba7afaa4070e21d2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-279e62f1201be7d6fe069802868fb4e8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-a0073a120dedc1faba7afaa4070e21d2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">


<meta name="citation_title" content="Exploring the Climate-Wine Relationship in Oregon">
<meta name="citation_author" content="Jennifer Arreola">
<meta name="citation_author" content="Rebekah M. Peterson">
<meta name="citation_author" content="Victoria Fox">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Economic impact study 2025: Oregon wine industry;,citation_author=WineAmerica;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://wineamerica.org/economic-impact-study-2025/oregon-wine-industry-2025/;">
<meta name="citation_reference" content="citation_title=The 2022 US census of agriculture: Insights for wine organizations and associations;,citation_author=Wine Data Researcher;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://winedataresearcher.com/the-2022-us-census-of-agriculture-insights-for-wine-organizations-and-associations/;">
<meta name="citation_reference" content="citation_title=Oregon vineyard and winery census;,citation_author=Oregon Wine Board;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://industry.oregonwine.org/research/oregon-vineyard-and-winery-report/;">
<meta name="citation_reference" content="citation_title=PRISM climate group;,citation_author=PRISM Climate Group, Oregon State University;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://www.prism.oregonstate.edu/;">
<meta name="citation_reference" content="citation_title=Climate change in the western united states grape growing regions;,citation_author=Gregory V. Jones;,citation_publication_date=2005;,citation_cover_date=2005;,citation_year=2005;,citation_journal_title=Acta Horticulturae;">
<meta name="citation_reference" content="citation_title=Temperature-based climate projections of pinot noir suitability in the willamette valley AVA;,citation_author=B. Skahill;,citation_author=B. Berenguer;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_publisher=Oregon Wine Symposium;">
<meta name="citation_reference" content="citation_title=Climate change projections indicate shifts in phenology for willamette valley pinot noir;,citation_author=L. M. Delelee;,citation_author=A. J. Woodill;,citation_author=P. A. Skinkis;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_journal_title=American Journal of Enology and Viticulture;">
<meta name="citation_reference" content="citation_title=Climate change impacts and adaptations of wine production;,citation_author=C. Van Leeuwen;,citation_author=others;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_journal_title=Nature Reviews Earth &amp;amp;amp; Environment;">
<meta name="citation_reference" content="citation_title=Effects of bunch heating on pinot noir grape ripening: Changes in berry anthocyanin and malic acid concentrations and their regulation;,citation_author=Jeffrey S. Bennett;,citation_author=others;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.frontiersin.org/journals/plant-physiology/articles/10.3389/fphgy.2025.1701827/abstract;,citation_journal_title=Frontiers in Plant Physiology;">
<meta name="citation_reference" content="citation_title=Diurnal temperature range compression hastens berry development and modifies flavonoid partitioning in grapes;,citation_author=Seth D. Cohen;,citation_author=Julie M. Tarara;,citation_author=James A. Kennedy;,citation_publication_date=2012;,citation_cover_date=2012;,citation_year=2012;,citation_fulltext_html_url=https://www.ajevonline.org/content/63/1/112;,citation_issue=1;,citation_volume=63;,citation_journal_title=American Journal of Enology and Viticulture;">
<meta name="citation_reference" content="citation_title=High temperature alters anthocyanin concentration and composition in grape berries of malbec, merlot, and pinot noir in a cultivar-dependent manner;,citation_author=Inés Rosas;,citation_author=Leonor Deis;,citation_author=Yésica Baldo;,citation_author=Juan B. Cavagnaro;,citation_author=Pablo F. Cavagnaro;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://pmc.ncbi.nlm.nih.gov/articles/PMC9003205/;,citation_journal_title=Plants;">
<meta name="citation_reference" content="citation_title=Low night temperature at veraison enhances the accumulation of anthocyanins in corvina grapes (vitis vinifera l.);,citation_author=Federica Gaiotti;,citation_author=Chiara Pastore;,citation_author=Ilaria Filippetti;,citation_author=Lorenzo Lovat;,citation_author=Nicola Belfiore;,citation_author=Diego Tomasi;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=https://www.nature.com/articles/s41598-018-26921-4;,citation_journal_title=Scientific Reports;">
<meta name="citation_reference" content="citation_title=Day temperature has a stronger effect than night temperature on anthocyanin and flavonol accumulation in ’merlot’ (vitis vinifera l.) grapes during ripening;,citation_author=Yifan Yan;,citation_author=Changzheng Song;,citation_author=Luigi Falginella;,citation_author=Simone D. Castellarin;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7396706/;,citation_journal_title=Frontiers in Plant Science;">
<meta name="citation_reference" content="citation_title=With climate change, nights are warming faster than days. why?;,citation_author=Kristina Dahl;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://blog.ucs.org/kristy-dahl/with-climate-change-nights-are-warming-faster-than-days-why/;,citation_publisher=Union of Concerned Scientists Blog;">
<meta name="citation_reference" content="citation_title=Increased asymmetric warming rates between daytime and nighttime temperatures over global land during recent decades;,citation_author=X. Liu;,citation_author=others;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2024GL112832;,citation_journal_title=Geophysical Research Letters;">
<meta name="citation_reference" content="citation_title=Site assessment;,citation_author=Gregory V. Jones;,citation_author=Edward Hellman;,citation_editor=Edward Hellman;,citation_publication_date=2003;,citation_cover_date=2003;,citation_year=2003;,citation_inbook_title=Oregon viticulture;">
<meta name="citation_reference" content="citation_title=Effect of controlled day and night temperatures on grape coloration;,citation_author=W. M. Kliewer;,citation_author=R. E. Torres;,citation_publication_date=1972;,citation_cover_date=1972;,citation_year=1972;,citation_fulltext_html_url=https://www.ajevonline.org/content/23/2/71;,citation_issue=2;,citation_volume=23;,citation_journal_title=American Journal of Enology and Viticulture;">
<meta name="citation_reference" content="citation_title=Impact of diurnal temperature variation on grape berry development, proanthocyanidin accumulation, and the expression of flavonoid pathway genes;,citation_author=Sarah D. Cohen;,citation_author=Julie M. Tarara;,citation_author=Gregory A. Gambetta;,citation_author=Mark A. Matthews;,citation_author=James A. Kennedy;,citation_publication_date=2012;,citation_cover_date=2012;,citation_year=2012;,citation_issue=7;,citation_doi=10.1093/jxb/err449;,citation_volume=63;,citation_journal_title=Journal of Experimental Botany;">
<meta name="citation_reference" content="citation_title=Willamette valley;,citation_author=Oregon Wine Board Trade Resources;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://trade.oregonwine.org/resources/willamette-valley/;">
<meta name="citation_reference" content="citation_title=What makes pinot noir burgundian or ’orgundian’;,citation_author=Stacy Briscoe;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://napavalleywineacademy.com/examining-the-environmental-influences-of-two-prominent-pinot-noir-regions/;,citation_publisher=Napa Valley Wine Academy;">
<meta name="citation_reference" content="citation_title=Tasting terroir: The climate effect;,citation_author=King Estate Winery;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://kingestate.com/tasting-terroir-the-climate-effect/;">
<meta name="citation_reference" content="citation_title=Willamette valley wine guide – pinot noir &amp;amp;amp; top AVAs;,citation_author=SommSelect;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://sommselect.com/blogs/tasting-notes/willamette-valley-wine-guide-history-regions-and-top-wines;">
</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Exploring the Climate-Wine Relationship in Oregon</h1>
            <p class="subtitle lead">Do climate variables affect wine yield in Oregon, and if so, when in the growing season do they matter most?</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                <div>
            <div class="quarto-title-meta-heading">Authors</div>
            <div class="quarto-title-meta-contents">
                        <p>Jennifer Arreola </p>
                        <p>Rebekah M. Peterson </p>
                        <p>Victoria Fox </p>
                      </div>
          </div>
                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a>
  <ul class="collapse">
  <li><a href="#pinot-noir-is-a-key-varietal-for-the-oregon-wine-industry" id="toc-pinot-noir-is-a-key-varietal-for-the-oregon-wine-industry" class="nav-link" data-scroll-target="#pinot-noir-is-a-key-varietal-for-the-oregon-wine-industry">Pinot Noir is a key varietal for the Oregon wine industry</a></li>
  </ul></li>
  <li><a href="#the-diurnal-range-effect" id="toc-the-diurnal-range-effect" class="nav-link" data-scroll-target="#the-diurnal-range-effect">The diurnal range effect</a>
  <ul class="collapse">
  <li><a href="#prior-research-on-oregon-and-pinot-noir-climate-sensitivity" id="toc-prior-research-on-oregon-and-pinot-noir-climate-sensitivity" class="nav-link" data-scroll-target="#prior-research-on-oregon-and-pinot-noir-climate-sensitivity">Prior research on Oregon and Pinot Noir climate sensitivity</a></li>
  <li><a href="#filling-an-availability-gap-for-oregon-wine-data" id="toc-filling-an-availability-gap-for-oregon-wine-data" class="nav-link" data-scroll-target="#filling-an-availability-gap-for-oregon-wine-data">Filling an availability gap for Oregon wine data</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data sources</a></li>
  <li><a href="#data-engineering-pipeline" id="toc-data-engineering-pipeline" class="nav-link" data-scroll-target="#data-engineering-pipeline">Data engineering pipeline</a></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations">Ethical considerations</a></li>
  <li><a href="#data-quality-caveats" id="toc-data-quality-caveats" class="nav-link" data-scroll-target="#data-quality-caveats">Data quality caveats</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#oregons-growing-reliance-on-pinot-noir" id="toc-oregons-growing-reliance-on-pinot-noir" class="nav-link" data-scroll-target="#oregons-growing-reliance-on-pinot-noir">Oregon’s growing reliance on Pinot Noir</a></li>
  <li><a href="#evidence-of-a-warming-climate" id="toc-evidence-of-a-warming-climate" class="nav-link" data-scroll-target="#evidence-of-a-warming-climate">Evidence of a warming climate</a></li>
  <li><a href="#how-the-climate-features-relate" id="toc-how-the-climate-features-relate" class="nav-link" data-scroll-target="#how-the-climate-features-relate">How the climate features relate</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#production-and-yield-have-so-far-kept-climbing" id="toc-production-and-yield-have-so-far-kept-climbing" class="nav-link" data-scroll-target="#production-and-yield-have-so-far-kept-climbing">Production and yield have, so far, kept climbing</a></li>
  <li><a href="#the-quality-concern-hiding-under-a-healthy-yield-trend" id="toc-the-quality-concern-hiding-under-a-healthy-yield-trend" class="nav-link" data-scroll-target="#the-quality-concern-hiding-under-a-healthy-yield-trend">The quality concern hiding under a healthy yield trend</a></li>
  <li><a href="#predicting-yield-across-the-growing-season" id="toc-predicting-yield-across-the-growing-season" class="nav-link" data-scroll-target="#predicting-yield-across-the-growing-season">Predicting yield across the growing season</a></li>
  <li><a href="#adjusting-for-class-imbalances" id="toc-adjusting-for-class-imbalances" class="nav-link" data-scroll-target="#adjusting-for-class-imbalances">Adjusting for class imbalances</a></li>
  <li><a href="#fitting-three-models-to-represent-a-sequential-growing-season" id="toc-fitting-three-models-to-represent-a-sequential-growing-season" class="nav-link" data-scroll-target="#fitting-three-models-to-represent-a-sequential-growing-season">Fitting three models to represent a sequential growing season</a></li>
  <li><a href="#climate-becomes-predictive-mid-season-then-declines" id="toc-climate-becomes-predictive-mid-season-then-declines" class="nav-link" data-scroll-target="#climate-becomes-predictive-mid-season-then-declines">Climate becomes predictive mid-season, then declines</a></li>
  <li><a href="#model-reliance-on-variety-identity-vs.-climate-features" id="toc-model-reliance-on-variety-identity-vs.-climate-features" class="nav-link" data-scroll-target="#model-reliance-on-variety-identity-vs.-climate-features">Model reliance on variety identity vs.&nbsp;climate features</a></li>
  <li><a href="#does-the-post-2020-period-leave-a-more-visible-mark-on-some-varieties" id="toc-does-the-post-2020-period-leave-a-more-visible-mark-on-some-varieties" class="nav-link" data-scroll-target="#does-the-post-2020-period-leave-a-more-visible-mark-on-some-varieties">Does the post-2020 period leave a more visible mark on some varieties?</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">Future work</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




  


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Rising global temperatures have raised concern for the viability of climate-sensitive crops nationwide, and few crops illustrate that exposure as directly as wine grapes. In Oregon, wine grapes underpin an industry worth $7.08 billion in annual economic activity, supporting nearly 40,000 jobs and $715 million in annual tourism spending <span class="citation" data-cites="wineamerica2025">(<a href="#ref-wineamerica2025" role="doc-biblioref">WineAmerica 2025</a>)</span>. Its flagship variety, Pinot Noir, is particularly exposed to the specific climate mechanisms driving that broader concern, a relationship we explore in detail throughout this report. More frequent heat waves and less predictable seasonal weather can shift vintage profiles and elevate the risk of disruptions like the wildfire smoke taint Oregon experienced amid the 2020 fires, which fell disproportionately on red wine varieties <span class="citation" data-cites="oregonwine2025willamette">(<a href="#ref-oregonwine2025willamette" role="doc-biblioref">Oregon Wine Board Trade Resources 2025</a>)</span>.</p>
<p>Oregon is home to 23 federally recognized American Viticultural Areas (AVAs), spanning distinct growing regions with meaningfully different climates. The Willamette Valley, which we split in our analysis into North and South Willamette Valley, sits near the 45th parallel under a cool, marine-influenced climate that gave rise to its Pinot Noir reputation in the first place. Further south and inland, the Rogue and Umpqua Valleys run warmer and drier, supporting a different varietal mix, while the Columbia River region spans Oregon’s northern border. Alongside Pinot Noir, Oregon growers plant substantial acreage of Pinot Gris, Chardonnay, Riesling, Gewürztraminer, and smaller amounts of Cabernet Sauvignon and Merlot in the state’s warmer regions<span class="citation" data-cites="oregonwine2025willamette">(<a href="#ref-oregonwine2025willamette" role="doc-biblioref">Oregon Wine Board Trade Resources 2025</a>)</span>. For this analysis, we grouped Oregon’s AVAs into five broader reporting regions: North Willamette Valley, South Willamette Valley, Rogue Valley, Umpqua, and Columbia River at Large, matching the geographic level at which usable historical production data is actually available.</p>
<div style="width: 100%; max-width: 950px; margin: 20px auto; border: 1px solid #ddd; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.08); overflow: hidden;">
<p><iframe src="https://019fc4eb-ccc6-ac48-3271-c2190ba05ae5.share.connect.posit.cloud/" width="100%" height="750px" style="border: none;"> </iframe></p>
</div>
<p>Willamette Valley Pinot Noir represents a disproportionate share of that production. While our aim is to understand climate exposure across all of Oregon’s varietals, Pinot Noir’s scale means it is also the variety for which we have the deepest historical record to draw on. This data asymmetry shapes how we approach analysis and interpret results.</p>
<p>Despite this economic and analytical importance, no single, interpretable public data source currently houses Oregon wine data, let alone production data alongside the climate data needed to study it. We describe the origin of this gap in Background, and closing it is one of the central goals of this project’s data engineering work.</p>
<p>This report asks a specific version of the broader climate question above: how has Oregon’s changing climate affected wine yield across its growing regions since 1987, and does that sensitivity differ by variety and by point in the growing season? We answer it in two stages. First, a statistical panel and correlation analysis establishes the historical relationship between Oregon’s climate indicators and yield. Second, a staged machine learning model tests when in the growing season (spring, summer, or harvest) climate information actually becomes predictive of yield, and for which varieties. That second stage carries the more interesting finding: nearly all of the model’s predictive power arrives once summer heat data is available, with harvest-season features adding noise and a slight decrease in performance. As we show later, that pattern lines up with a separate finding that late-season climate is a signal for wine quality rather than yield.</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<section id="pinot-noir-is-a-key-varietal-for-the-oregon-wine-industry" class="level2">
<h2 class="anchored" data-anchor-id="pinot-noir-is-a-key-varietal-for-the-oregon-wine-industry">Pinot Noir is a key varietal for the Oregon wine industry</h2>
<p>Among wine producers, Pinot Noir is known for being a very difficult grape due to its thin skin, tight grape clusters, early ripening, and sensitivity to heat. For many years, Pinot Noir production was limited to regions like Burgundy, France that had a narrow band of warm, sunny days during the growing season paired with a pronounced overnight cooldown—ideal conditions for the slow, gentle ripening required for great Pinot Noir.</p>
<p>In the 1960s, the winemaker David Lett set out to find a region outside of Burgundy where he could successfully cultivate Pinot Noir vines. He settled in Oregon’s Willamette Valley, which sits on the same latitude as Burgundy (close to the 45th parallel) and has been assessed as sharing many of the same climate characteristics relevant to Pinot Noir viticultural site selection <span class="citation" data-cites="jonesHellman2003">(<a href="#ref-jonesHellman2003" role="doc-biblioref">Jones and Hellman 2003</a>)</span>, including the day-night temperature swing that is vital to Pinot Noir’s unique character. In 1979, Lett entered his Willamette Valley Pinot Noir in the Gault-Millau French Wine Olympiad, where he placed among the top Burgundies. This was the first real signal that Oregon could compete at the same level as the region that had produced the best Pinot Noirs for hundreds of years <span class="citation" data-cites="oregonwine2025willamette">(<a href="#ref-oregonwine2025willamette" role="doc-biblioref">Oregon Wine Board Trade Resources 2025</a>)</span>. The Willamette Valley became an official American Viticultural Area (AVA) in 1983 and has since become one of the most recognized Pinot Noir regions in the world, a status widely attributed to its warm-day, cool-night climate pattern <span class="citation" data-cites="oregonwine2025willamette sommselect2026">(<a href="#ref-oregonwine2025willamette" role="doc-biblioref">Oregon Wine Board Trade Resources 2025</a>; <a href="#ref-sommselect2026" role="doc-biblioref">SommSelect 2026</a>)</span>. This unique climate pattern is referred to as <em>diurnal temperature range</em>.</p>
</section>
</section>
<section id="the-diurnal-range-effect" class="level1">
<h1>The diurnal range effect</h1>
<p>Warm days drive photosynthesis and sugar accumulation in the grapes, while cool nights slow the grape’s respiration rate, giving time for the acids, color compounds, and aromatic molecules to further develop rather than burning off overnight. Without this nightly cooldown, grapes ripen too fast and produce wines that taste “flat”—high in sugar without the balance of acidity and aromatic complexity that define great Pinot Noir <span class="citation" data-cites="kliewer1972 ajev2012dtr">(<a href="#ref-kliewer1972" role="doc-biblioref">Kliewer and Torres 1972</a>; <a href="#ref-ajev2012dtr" role="doc-biblioref">Seth D. Cohen et al. 2012</a>)</span>.</p>
<p>An ideal diurnal range for Pinot Noir ripening is generally considered to be in the neighborhood of 15–20°C (~60-70°F). Controlled field and growth-chamber experiments on Pinot Noir have shown that raising the diurnal temperature range around the onset of ripening (<em>veraison</em>) alters organic acid metabolism and can inhibit color and phenolic accumulation in the grape <span class="citation" data-cites="frontiers2025bunchheating cohen2012jexpbot">(<a href="#ref-frontiers2025bunchheating" role="doc-biblioref"><span class="nocase">Bennett et al.</span> 2025</a>; <a href="#ref-cohen2012jexpbot" role="doc-biblioref">Sarah D. Cohen et al. 2012</a>)</span>. While compression of the diurnal range has been shown to hasten ripening and shift how flavors develop in wine grapes broadly <span class="citation" data-cites="ajev2012dtr">(<a href="#ref-ajev2012dtr" role="doc-biblioref">Seth D. Cohen et al. 2012</a>)</span>, targeted studies on Malbec, Merlot, and Pinot Noir have found that diurnal range sensitivity is not universal across varieties and is particularly pronounced in Pinot Noir <span class="citation" data-cites="pmc2022highTemp">(<a href="#ref-pmc2022highTemp" role="doc-biblioref">Rosas et al. 2022</a>)</span>.</p>
<p>When we consider the impact of climate on wine production, particularly in Oregon where Pinot Noir is the dominant variety, it is not just a question of whether summers are getting hotter <em>overall</em>, but rather what happens when <em>nights warm faster than days</em>. This is a documented feature of twentieth- and twenty-first-century climate shifts globally, generally attributed to changes in cloud cover trapping heat overnight <span class="citation" data-cites="ucs2022nights liu2024dtr">(<a href="#ref-ucs2022nights" role="doc-biblioref">Dahl 2022</a>; <a href="#ref-liu2024dtr" role="doc-biblioref"><span class="nocase">Liu et al.</span> 2024</a>)</span>. This is exactly the pattern we observe in Oregon’s climate record: a real warming signal in growing degree days and heat stress, alongside shrinking day-night temperature swings during ripening <span class="citation" data-cites="ucs2022nights liu2024dtr">(<a href="#ref-ucs2022nights" role="doc-biblioref">Dahl 2022</a>; <a href="#ref-liu2024dtr" role="doc-biblioref"><span class="nocase">Liu et al.</span> 2024</a>)</span>.</p>
<section id="prior-research-on-oregon-and-pinot-noir-climate-sensitivity" class="level2">
<h2 class="anchored" data-anchor-id="prior-research-on-oregon-and-pinot-noir-climate-sensitivity">Prior research on Oregon and Pinot Noir climate sensitivity</h2>
<p>Climate research specific to Oregon wine has, to date, focused primarily on phenology and single-variety climate suitability rather than on production outcomes directly. Multi-decade climate analyses have documented measurable statewide warming, pushing the Willamette Valley from sitting at the cool edge of Pinot Noir suitability in the 1960-70s to sitting centered within that suitability range today <span class="citation" data-cites="jones2005">(<a href="#ref-jones2005" role="doc-biblioref">Jones 2005</a>)</span>. Work presented at the Oregon Wine Symposium has projected temperature-driven shifts in Oregon varietal suitability and harvest timing through 2100, pointing toward a potential reshuffling of the state’s variety composition as the climate continues to warm <span class="citation" data-cites="skahill2025">(<a href="#ref-skahill2025" role="doc-biblioref">Skahill and Berenguer 2025</a>)</span>. Separately, phenological modeling published in the <em>American Journal of Enology and Viticulture</em> has modeled shifts in the timing of the Willamette Valley’s Pinot Noir growing season, reinforcing the variety’s particular sensitivity to the region’s climate <span class="citation" data-cites="delelee2025">(<a href="#ref-delelee2025" role="doc-biblioref">Delelee et al. 2025</a>)</span>.</p>
<p>We draw our general climate-threshold framework (frost days, growing degree days, heat stress days) from a global synthesis of viticulture climate impacts <span class="citation" data-cites="vanleeuwen2024">(<a href="#ref-vanleeuwen2024" role="doc-biblioref"><span class="nocase">Van Leeuwen et al.</span> 2024</a>)</span>. This project differs from that body of work in that, rather than modeling suitability or phenology on their own, we integrate 38 years of statewide production records directly with climate data to ask whether the warming trend has affected <em>production outcomes</em>, not just suitability.</p>
</section>
<section id="filling-an-availability-gap-for-oregon-wine-data" class="level2">
<h2 class="anchored" data-anchor-id="filling-an-availability-gap-for-oregon-wine-data">Filling an availability gap for Oregon wine data</h2>
<p>Our motivation for this project is also driven by a genuine gap in publicly available data for Oregon wines. Due to the fact that 90% of U.S. wine grape acreage sits in California and Washington, USDA’s National Agricultural Statistics Service (NASS) discontinued collecting Oregon-specific grape data beginning in 2011 <span class="citation" data-cites="nass2011gap">(<a href="#ref-nass2011gap" role="doc-biblioref">Wine Data Researcher 2022</a>)</span>. While similar data continued to be collected by researchers in Oregon, this information existed largely as scanned PDF reports rather than structured data. This project’s data engineering work is built in part to close that gap by producing a structured, climate-linked Oregon wine dataset that does not currently exist from any single public source.</p>
</section>
</section>
<section id="data" class="level1">
<h1>Data</h1>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">Data sources</h2>
<p><strong>Oregon wine production and pricing</strong> data comes from the Oregon Vineyard and Winery Annual Reports, conducted since 1981 by various research groups and currently maintained by the University of Oregon <span class="citation" data-cites="oregonwinecensus">(<a href="#ref-oregonwinecensus" role="doc-biblioref">Oregon Wine Board 2026</a>)</span>. Reports prior to 2017 exist only as scanned &amp; digital PDF documents and were ingested using AWS Textract; later years were ingested directly from structured spreadsheets.</p>
<p><strong>Climate data</strong> was retrieved from the PRISM Climate Group, maintained by Oregon State University. PRISM provides daily gridded temperature and precipitation observations across the contiguous United States <span class="citation" data-cites="prism2026">(<a href="#ref-prism2026" role="doc-biblioref">PRISM Climate Group, Oregon State University 2026</a>)</span>. We retrieved daily observations from 1981-2024 across all 23 federally-recognized AVAs in Oregon. Zonal statistics were produced for each AVA by averaging the raster grid within each AVA boundary using the Python rasterstats library. AVA boundaries were defined by shapefiles obtained from the Alcohol and Tobacco Tax and Trade Bureau (TTB), which were converted to GeoJSON prior to their use in the ingestion script.</p>
<p>From the daily climate data, we derived a set of features chosen specifically for their relevance to viticulture, rather than working with raw daily temperature and precipitation directly.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frost risk days</td>
<td>Count of days below freezing, annually and during the April–May bud-break window</td>
</tr>
<tr class="even">
<td>Coldest spring night</td>
<td>Minimum recorded temperature during spring bud-break</td>
</tr>
<tr class="odd">
<td>Growing degree days (GDD)</td>
<td>Accumulated heat above a 10°C (50°F) base, April–September (Winkler index), plus a April–October variant and a July 15–October 15 “veraison-to-harvest” window</td>
</tr>
<tr class="even">
<td>Heat stress days</td>
<td>Count of days with a maximum temperature above 35°C (95°F) during the growing season</td>
</tr>
<tr class="odd">
<td>Vapor pressure deficit (VPD)</td>
<td>A measure of atmospheric dryness / evaporative demand, computed for summer (July–August) and ripening (August–September) windows</td>
</tr>
<tr class="even">
<td>Diurnal temperature range (ripening)</td>
<td>Average day-night temperature swing during August–September, the period when grapes develop their sugar, color, and acidity</td>
</tr>
<tr class="odd">
<td>Harvest precipitation</td>
<td>Total precipitation in October, and in the September–October window</td>
</tr>
</tbody>
</table>
</section>
<section id="data-engineering-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="data-engineering-pipeline">Data engineering pipeline</h2>
<p>Climate and production data were ingested on a recurring Amazon Web Services (AWS) batch pipeline (one task per AVA), computed into region- and statewide-level summaries, and stored in a PostgreSQL database hosted on Railway. AWS was chosen specifically for the production-data side of the pipeline, as reconstructing tables from PDF reports required routing each report era through separate Textract-based parsers due to varied report formats, column layouts, and label conventions. For the climate data, daily PRISM rasters were cached prior to computing zonal statistics, which were then written to the database via an idempotent upsert. Running this pipeline on AWS Batch / Fargate Spot allowed each AVA to be processed as a parallel, independently retriable job, though Spot interruptions during the original run caused some days to be missed; these were identified and backfilled in a final pass before the analysis tables were built.</p>
<p>Two analysis-ready tables were constructed on top of the raw data:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Panel</th>
<th>Coverage</th>
<th>Grain</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Regional panel</td>
<td>1987-2024</td>
<td>One row per region x variety x year</td>
<td>Yield modeling and region-level comparisons</td>
</tr>
<tr class="even">
<td>Statewide panel</td>
<td>1987-2024</td>
<td>One row per variety x year</td>
<td>Long-run varietal-mix analysis where regional detail is unnecessary</td>
</tr>
</tbody>
</table>
<p>Both panels begin in 1987, rather than 1981, because of limitations in the production data. While the full PRISM climate dataset was available from 1981 for all AVAs, the underlying wine census reports for 1981-1986 do not contain the area-by-variety breakdown tables needed to reconstruct regional variety data. These reports <em>do</em> contain bearing and non-bearing acreage by county, which could in principle be aggregated to the region level for an acreage-only (not variety-level) time series; we did not pursue this, and instead clipped both panels to 1987 onward to keep the regional and statewide tables consistent.</p>
<p>Region-variety combinations were filtered to those with at least 20 years of historical data and zero-production / zero-harvest rows were dropped. This reduced the original ~1,300 region-variety-year observations to ~990 in the regional panel.</p>
<p>The analysis tables were exported to Parquet files, which are used as the final data references for this report to preserve reproducibility. Our long-term goal is to make the underlying database publicly available, but this is a continued work in progress.</p>
</section>
<section id="ethical-considerations" class="level2">
<h2 class="anchored" data-anchor-id="ethical-considerations">Ethical considerations</h2>
<p>A few ethical considerations shaped how we approached this dataset:</p>
<ol type="1">
<li><strong>Regional underrepresentation:</strong> Underlying wine census data is reported by region, not by individual vineyard or winery, and is a voluntary industry survey rather than a full census. We recognize that this led to underrepresentation for some counties in some years.</li>
<li><strong>Diversity and inclusion gaps among Oregon wine producers:</strong> Because there are very few minority-owned wineries in Oregon—our research turned up only two Native-owned wineries statewide—there is a real possibility that patterns related to these ownership demographics are invisible in this dataset. The effect of climate may have a disproportionate impact on some groups over others, but data was never collected that could surface these patterns.</li>
<li><strong>Impact of immigration on Oregon wine production:</strong> Recent immigration policy has affected farmworkers and their families in ways that are impossible to quantify from production statistics alone. The truth is that Oregon wine production relies heavily on seasonal immigrant labor, and the raw production numbers do not tell the human story of these populations who are increasingly at risk in American society.</li>
</ol>
<p>We treat this dataset as a record of production and climate outcomes only, not as a complete picture of the people who participate in the industry that these outcomes describe.</p>
</section>
<section id="data-quality-caveats" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-caveats">Data quality caveats</h2>
<p>We would like to provide transparency with respect to some key tradeoffs in our data collection:</p>
<ul>
<li><strong>Pre-2002 regional variety data is reconstructed, not directly reported.</strong> From 1987–2001, the industry reports at the statewide level did not break variety out by region; those years were reconstructed by aggregating county-level figures up to reporting regions. North Willamette Valley acreage, for example, is undercounted by roughly 15–20% for years before 1999 because the source area tables for that era only list major counties. This undercount only affects the variety-level breakdown for that region; the “all varieties” total is accurate. We treat pre-2002 regional findings with corresponding caution throughout this report and do not present county-aggregated reconstructions as precise counts.</li>
<li><strong>Regional and statewide panels begin in 1987, not 1981, despite full climate coverage back to 1981</strong>: As described above, this is driven entirely by gaps in the wine production data source tables, not by any limitation in the climate data.</li>
<li><strong>Price per ton (<code>PRI_01</code>) is only available at the region level from 2010 onward.</strong> This is a genuine limitation of the source data and constrains how far back any price-based analysis can go. Additionally, because price is affected by many factors, of which climate is only one, our analysis centers mainly around production data rather than price data.</li>
<li><strong>The wine census is self-reported and voluntary, not a full census.</strong> We treat year-to-year volatility in the raw production series with more caution than the smoothed, multi-year trends.</li>
</ul>
<p>None of these caveats change our core findings, which are drawn primarily from long-term trends and the more reliable 2002–2024 window and from the climate data which has no comparable gaps. PRISM provides complete daily coverage for all 23 AVAs across the full 1981–2024 period.</p>
</section>
</section>
<section id="analysis" class="level1">
<h1>Analysis</h1>
<section id="oregons-growing-reliance-on-pinot-noir" class="level2">
<h2 class="anchored" data-anchor-id="oregons-growing-reliance-on-pinot-noir">Oregon’s growing reliance on Pinot Noir</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/pinot_dominance-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure 1: Statewide grape tonnage by variety, 1987–2024"><img src="capstone_files/figure-html/pinot_dominance-1.png" class="img-fluid figure-img" width="672" alt="Figure 1: Statewide grape tonnage by variety, 1987–2024"></a></p>
<figcaption>Figure 1: Statewide grape tonnage by variety, 1987–2024</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 1 demonstrates Pinot Noir’s growing share of statewide tonnage, from roughly 15% in 1990 to around 30% by 2020. This trend has continued to build, while other anchor varieties like Chardonnay and Riesling have declined sharply over the same period. Pinot Gris is one variety that counteracts this trend, growing from a negligible share in 1990 to a stable ~8% by 2010.</p>
<p>However, the dramatic shift toward Pinot Noir has remained a dominant trend, suggesting that Oregon’s wine industry has increasingly concentrated on climate-sensitive Pinot varieties over exactly the same decades that have coincided with a pronounced shift in the region’s key climate indicators.</p>
</section>
<section id="evidence-of-a-warming-climate" class="level2">
<h2 class="anchored" data-anchor-id="evidence-of-a-warming-climate">Evidence of a warming climate</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/gdd_statewide-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure 2: Growing degree day (GDD) anomaly relative to the 38-year average, overlaid with a 10-year rolling average"><img src="capstone_files/figure-html/gdd_statewide-1.png" class="img-fluid figure-img" width="672" alt="Figure 2: Growing degree day (GDD) anomaly relative to the 38-year average, overlaid with a 10-year rolling average"></a></p>
<figcaption>Figure 2: Growing degree day (GDD) anomaly relative to the 38-year average, overlaid with a 10-year rolling average</figcaption>
</figure>
</div>
</div>
</div>
<p>Growing degree days (GDDs) show a clear and sustained upward trend, with a level shift identified by a structural-break test around 2012.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/climate_indicators-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure 3: Six viticulture-relevant climate indicators, statewide average, 1987–2024, each with a linear trend and 95% confidence interval"><img src="capstone_files/figure-html/climate_indicators-1.png" class="img-fluid figure-img" width="672" alt="Figure 3: Six viticulture-relevant climate indicators, statewide average, 1987–2024, each with a linear trend and 95% confidence interval"></a></p>
<figcaption>Figure 3: Six viticulture-relevant climate indicators, statewide average, 1987–2024, each with a linear trend and 95% confidence interval</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 3 summarizes six key viticultural climate indicators. Growing degree days, peak summer temperature, and heat stress days are all trending up with tight confidence intervals, demonstrating a warming signal is both real and steep. Spring frost days are essentially flat, a meaningful non-finding since it means the warming trend has not reduced the risk of a damaging frost event during spring bud break, even as summer heat accumulation climbs. October precipitation trends slightly upward but noisily, with no strong signal either way.</p>
<p>The sixth indicator—ripening-season diurnal temperature range—is the one metric that moves in the opposite direction from the rest, and it does so specifically because it isn’t a simple byproduct of an overall upward heat trend. This finding is most directly relevant to Oregon’s growing dependence on Pinot Noir, since Pinot Noir relies on a wide day-night temperature swing during ripening to retain acidity and develop aromatic complexity—a mechanism we discussed in <a href="#background">Background</a>.</p>
</section>
<section id="how-the-climate-features-relate" class="level2">
<h2 class="anchored" data-anchor-id="how-the-climate-features-relate">How the climate features relate</h2>
<p>Several of these climate measures are closely related to aspects of the same underlying warming trend.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/climate_correlations-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure 4: Correlation matrix of annual climate features, statewide, 1987–2024"><img src="capstone_files/figure-html/climate_correlations-1.png" class="img-fluid figure-img" width="672" alt="Figure 4: Correlation matrix of annual climate features, statewide, 1987–2024"></a></p>
<figcaption>Figure 4: Correlation matrix of annual climate features, statewide, 1987–2024</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 4 identifies three clusters of variables that appear to measure largely the same underlying phenomenon from different angles, rather than independent drivers:</p>
<ol type="1">
<li><strong>Spring frost risk:</strong> Frost risk days and coldest spring night are correlated at -0.91, which makes sense given one is a temperature reading and the other is a threshold-count derived from it.</li>
<li><strong>Summer heat accumulation:</strong> Heat stress days and summer VPD are both correlated above 0.6 with all the GDD variables.</li>
<li><strong>Fall precipitation:</strong> Precipitation measures move together above 0.4.</li>
</ol>
<p>We also note that diurnal ripening temperature range is negatively correlated with nearly every heat-related feature, consistent with the pattern described in <a href="#background">Background</a>, where nights warm faster than days as the season heats up overall, compressing the day-night swing. Additionally, growing-season precipitation is negatively correlated with GDD Apr-Sep (-0.11), indicating that hotter years also tend to be drier years overall.</p>
<p>To resolve which variables to retain for modeling, we turn to variance inflation factors (VIF) to capture multi-variable overlap.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variance Inflation Factors</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sep-Oct precip</td>
<td style="text-align: right;">8.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oct precip</td>
<td style="text-align: right;">6.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Summer VPD</td>
<td style="text-align: right;">6.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coldest spring night</td>
<td style="text-align: right;">4.38</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GDD Apr-Sep</td>
<td style="text-align: right;">4.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frost risk days</td>
<td style="text-align: right;">3.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Heat stress days</td>
<td style="text-align: right;">2.90</td>
</tr>
<tr class="even">
<td style="text-align: left;">GDD Veraison-Harvest</td>
<td style="text-align: right;">2.34</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diurnal temp range</td>
<td style="text-align: right;">2.27</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Sep-Oct precipitation and Oct precipitation come out highest, confirming we should not include both in the model. We elected to drop Sep-Oct precipitation, as we recognize Oct precipitation specifically as an important botrytis / harvest-timing risk.</p>
<p>Surprisingly, Summer VPD is <em>higher</em> than GDD Apr-Sep (6.43 vs.&nbsp;4.13), even though the correlation matrix showed VPD’s strongest pairwise correlation was with GDD. This tells us Summer VPD is well-explained by some <em>combination</em> of GDD Apr-Sep, heat stress days, and ripening temp range together, rather than by a strong individual pairwise correlation with any one of them. We elect to drop GDD Apr-Sep and keep Summer VPD, as it is the more direct measure of vine water stress.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Variance Inflation Factors</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coldest spring night</td>
<td style="text-align: right;">4.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frost risk days</td>
<td style="text-align: right;">3.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Summer VPD</td>
<td style="text-align: right;">3.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat stress days</td>
<td style="text-align: right;">2.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GDD Veraison-Harvest</td>
<td style="text-align: right;">2.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diurnal temp range</td>
<td style="text-align: right;">1.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oct precip</td>
<td style="text-align: right;">1.15</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>All remaining VIFs fall under a conservative threshold of VIF&lt;5. Our retained predictor set going into the modeling stage is:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Frost risk days</td>
<td>Count of days below freezing during the April–May bud-break window</td>
</tr>
<tr class="even">
<td>Coldest spring night</td>
<td>Minimum recorded temperature during spring bud-break</td>
</tr>
<tr class="odd">
<td>GDD (Veraison–Harvest)</td>
<td>Accumulated heat above a 10°C (50°F) base during July 15–October 15 “veraison-to-harvest” window</td>
</tr>
<tr class="even">
<td>Heat stress days</td>
<td>Count of days with a maximum temperature above 35°C (95°F) during the growing season</td>
</tr>
<tr class="odd">
<td>Summer VPD</td>
<td>A measure of atmospheric dryness / evaporative demand during July–August</td>
</tr>
<tr class="even">
<td>Diurnal temperature range (ripening)</td>
<td>Average day-night temperature swing during August–September, the period when grapes develop their sugar, color, and acidity</td>
</tr>
<tr class="odd">
<td>Harvest precipitation (October)</td>
<td>Total precipitation in October</td>
</tr>
</tbody>
</table>
<p>Note that GDD Apr-Sep itself remains central to the <em>descriptive</em> climate trends in Figures 2–3 above; it is excluded only from the predictive feature set, where its information is substantially redundant with the other retained heat measures.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="production-and-yield-have-so-far-kept-climbing" class="level2">
<h2 class="anchored" data-anchor-id="production-and-yield-have-so-far-kept-climbing">Production and yield have, so far, kept climbing</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/total_production-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure 5: Statewide production-weighted yield, 1987–2024, with separate smoothed trends fit around 2002 reporting methodology shift"><img src="capstone_files/figure-html/total_production-1.png" class="img-fluid figure-img" width="672" alt="Figure 5: Statewide production-weighted yield, 1987–2024, with separate smoothed trends fit around 2002 reporting methodology shift"></a></p>
<figcaption>Figure 5: Statewide production-weighted yield, 1987–2024, with separate smoothed trends fit around 2002 reporting methodology shift</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 5 plots statewide production-weighted yield (total tons produced divided by total acres harvested) for every year from 1987 to 2024. This isolates how productive Oregon’s vineyard acreage has become over time, independent of how much new acreage has been planted. The thin gray line traces the raw annual totals as reported while the bold red trend line summarizes the underlying pattern using a smoothed fit. Harvested acreage expanded by roughly the same order of magnitude as raw production did over this period, which means most of the industry’s growth has come from planting more acres rather than from getting more productive per acre. Yield itself has seen modest growth, averaging around ~2.5 tons per acre in 1990s and 2000s and settling closer to ~3 tons per acre in the most recent decade.</p>
<p>We note a clear interruption in 2020, corresponding to a season with severe wildfire smoke taint that resulted in a substantial share of unusable fruit among that year’s harvest. This represents a discrete event rather than a gradual climate-trend effect.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/yield_by_variety-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure 6: Production-weighted yield by variety"><img src="capstone_files/figure-html/yield_by_variety-1.png" class="img-fluid figure-img" width="672" alt="Figure 6: Production-weighted yield by variety"></a></p>
<figcaption>Figure 6: Production-weighted yield by <strong>variety</strong></figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 6 breaks down the production-weighted yield for each of the four leading varietals: Chardonnay, Pinot Gris, Pinot Noir, and Riesling. Each panel repeats the same visual structure as Figure 5: a thin line for the raw annual value and a bold smoothed trend layered on top.</p>
<p>We see a dramatic dip in Pinot Noir yield in 2020 while Pinot Gris and Chardonnay barely register the disruption comparatively. This selective impact is consistent with wildfire smoke taint, which binds more readily to red wine grapes because of their extended skin-contact fermentation process than to white wine production; anecdotally, 2020 also drove some producers toward “white Pinot” as a workaround, itself a sign of the industry’s adaptive capacity.</p>
<p>All varieties rebound to new all-time highs within three years. Indeed, outside of that one disrupted year, yield for Pinot Noir and the other key varieties has held steady or trended upward statewide, and the same holds when the data is cut by region instead of variety in Figure 7 (below). The historical pattern demonstrates that, within the range of GDD and heat stress Oregon has experienced thus far, warmer conditions have generally corresponded with higher yields per acre across nearly every variety and region.</p>
<p>However, this pattern is not uniform across varieties. Pinot Gris demonstrated the largest yield gain of the four key varieties (roughly a 35% increase), with Pinot Noir close behind (44%) and Chardonnay more modest (34%). In contrast, Riesling shows essentially no relationship between yield and warmth of the growing season (-2%). This could be attributed to the fact that its production is concentrated largely in the cooler North Willamette Valley that rarely experiences the warmer end of the state’s climate range.</p>
<p>We also note that Pinot Gris’ rising share of statewide production (Figure 1) is attributable not only to an increasing share of planted acres, but also because this variety appears to yield higher volumes in the warmer seasons that are becoming increasingly common in Oregon.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/yield_by_region-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure 7: Production-weighted yield by region"><img src="capstone_files/figure-html/yield_by_region-1.png" class="img-fluid figure-img" width="672" alt="Figure 7: Production-weighted yield by region"></a></p>
<figcaption>Figure 7: Production-weighted yield by <strong>region</strong></figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 7 repeats the same weighted-yield calculation from Figure 6, this time faceted by Oregon’s five wine-growing regions rather than by variety. Yield across nearly every region has held steady or trended upward, reinforcing our observation that, within the climate range Oregon has experienced so far, warming has generally not come at the cost of yield and in many regions it has coincided with higher yields overall.</p>
<p>Umpqua is the one region that breaks this pattern. To examine this trend in more detail, Table 1 (below) lays out four growing-season climate metrics for each region, averaged over 2002–2024, with regions ordered from warmest to coolest.</p>
<div class="cell" data-tbl-cap="Table 1: Average growing-season climate by region, 2002–2024, ranked warmest to coolest">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1: Average growing-season climate by region, 2002–2024, ranked warmest to coolest</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">Mean GDD (Apr-Sep)</th>
<th style="text-align: right;">Mean summer high (°C)</th>
<th style="text-align: right;">Mean heat stress days</th>
<th style="text-align: right;">Mean ripening diurnal range (°C)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Columbia River at Large</td>
<td style="text-align: right;">1363</td>
<td style="text-align: right;">30.8</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">16.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rogue Valley</td>
<td style="text-align: right;">1301</td>
<td style="text-align: right;">30.6</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">17.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Umpqua</td>
<td style="text-align: right;">1212</td>
<td style="text-align: right;">28.9</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">16.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Willamette Valley</td>
<td style="text-align: right;">1162</td>
<td style="text-align: right;">27.8</td>
<td style="text-align: right;">4.3</td>
<td style="text-align: right;">14.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Willamette Valley</td>
<td style="text-align: right;">1154</td>
<td style="text-align: right;">28.6</td>
<td style="text-align: right;">5.4</td>
<td style="text-align: right;">16.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Columbia River at Large is a clear outlier at the warm end, and the two Willamette Valley sub-regions anchor the cool end, with Rogue Valley and Umpqua occupying the middle of the range. We note that Umpqua ranks third of five regions by growing degree days, meaningfully warmer than either Willamette Valley sub-region, yet it has both the lowest-weighted yield of any region over 2002–2024 and by far the flattest yield trend over that period. In contrast, Columbia River at Large shows a yield trajectory that is consistent with other regions, indicating that the yield trend is not tied to temperature alone. Umpqua’s yield story may be driven by other factors unrelated to the climate variables tracked by our dataset. Potential factors could include variety mix, vineyard scale, soil composition, or terrain complexity. We flag it here as a pattern worth further investigation rather than a settled finding.</p>
<p>Our overall observation is that warmer temperatures appear to have limited or somewhat positive impact on yield. However, warmer seasons can raise yield while simultaneously degrading the flavor and quality characteristics that define Oregon’s premium wines, particularly Pinot Noir.</p>
</section>
<section id="the-quality-concern-hiding-under-a-healthy-yield-trend" class="level2">
<h2 class="anchored" data-anchor-id="the-quality-concern-hiding-under-a-healthy-yield-trend">The quality concern hiding under a healthy yield trend</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/diurnal_shift-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure 8: Diurnal ripening temperature range, statewide average, 1981–2024, shown against the ideal 15–20°C range for Pinot Noir ripening"><img src="capstone_files/figure-html/diurnal_shift-1.png" class="img-fluid figure-img" width="672" alt="Figure 8: Diurnal ripening temperature range, statewide average, 1981–2024, shown against the ideal 15–20°C range for Pinot Noir ripening"></a></p>
<figcaption>Figure 8: Diurnal ripening temperature range, statewide average, 1981–2024, shown against the ideal 15–20°C range for Pinot Noir ripening</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 8 demonstrates a diurnal range that has narrowed from roughly 17°C in the 1980s to roughly 15°C today, indicating that nights are warming faster than days. This is consistent with a pattern documented globally in the climate literature and generally attributed to changes in cloud cover trapping heat overnight <span class="citation" data-cites="ucs2022nights liu2024dtr">(<a href="#ref-ucs2022nights" role="doc-biblioref">Dahl 2022</a>; <a href="#ref-liu2024dtr" role="doc-biblioref"><span class="nocase">Liu et al.</span> 2024</a>)</span>. This day-night temperature swing is a key mechanism behind Oregon’s suitability for growing Pinot Noir: warm days build sugar, while cool nights slow the grape’s respiration long enough to retain complex acidity, color, and aromatic qualities in the grape <span class="citation" data-cites="ajev2012dtr">(<a href="#ref-ajev2012dtr" role="doc-biblioref">Seth D. Cohen et al. 2012</a>)</span>. Controlled experiments on Pinot Noir, specifically, have found that compressing this range alters organic acid metabolism and can suppress color accumulation, and a companion study found Pinot Noir was one of the varieties most sensitive to elevated diurnal temperature among the major red varieties tested <span class="citation" data-cites="frontiers2025bunchheating pmc2022highTemp">(<a href="#ref-frontiers2025bunchheating" role="doc-biblioref"><span class="nocase">Bennett et al.</span> 2025</a>; <a href="#ref-pmc2022highTemp" role="doc-biblioref">Rosas et al. 2022</a>)</span>.</p>
<p>This narrowing diurnal range is a potential risk to wine <em>quality</em> that has not surfaced in the production metrics alone. Diurnal range operates on wine quality through a physiological process that is more nuanced than heat-accumulation metrics in isolation, and models built on yield alone will miss this leading indicator entirely. Future research could evaluate this risk through proxy indicators of wine quality such as price premiums or critic-score text mining.</p>
</section>
<section id="predicting-yield-across-the-growing-season" class="level2">
<h2 class="anchored" data-anchor-id="predicting-yield-across-the-growing-season">Predicting yield across the growing season</h2>
<p>Next, we aim to create a predictive model built on two key observations from our analysis thus far: (1) yield has been resilient across the historical climate range and (2) the climate signal accumulates in stages over the course of the growing season. We argue that a model built only on a single end-of-season snapshot is less useful to a wine grower who experiences these climate conditions sequentially throughout the annual growth cycle.</p>
<p>Insights derived from our predictive model are intended to help wine growers understand not only what climate interactions have the ability to impact yield, but when those impacts would be most visible in the growing season, and for which varieties they matter most. We modeled yield_derived (production tons per harvested acre) using a Support Vector Machine (SVM) with a radial basis function (RBF) kernel, tuned via Cross-Validation (CV). An SVM was selected because the usable sample, roughly 1,000 region-by-variety-year observations, is small enough that a kernel method with relatively few tunable parameters is less prone to overfitting, while the RBF kernel still captures the non-linear climate-yield relationships suggested by our correlation analysis. Our small observation size contained class imbalances in varietal observations, particularly in Merlot and Pinot Blanc, where Pinot Blanc’s imbalance ratio against Pinot Noir was 3.7x, that were balanced in the training data through weighting samples by inverse frequency.</p>
</section>
<section id="adjusting-for-class-imbalances" class="level2">
<h2 class="anchored" data-anchor-id="adjusting-for-class-imbalances">Adjusting for class imbalances</h2>
<ul>
<li>Weight = inverse of how many rows that variety-by-region combination has, normalized so weights average to 1</li>
<li>Down-weights the influence of well-represented groups (Pinot Noir, North Willamette Valley) relative to thin ones (Pinot Blanc, Merlot)</li>
</ul>
<p>Table 2 shows the resulting sample weight for each region-by-variety combination, ranked from most to least up-weighted. Groups with the fewest rows receive the largest weights, so the model treats each combination as roughly equally informative during training rather than letting the best-sampled groups (Pinot Noir, Chardonnay) dominate simply because they have more rows.</p>
<div class="cell" data-tbl-cap="Table 2: Sample weight by region and variety combination (most and least up-weighted)">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 2: Sample weight by region and variety combination (most and least up-weighted)</caption>
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Variety</th>
<th style="text-align: right;">N rows</th>
<th style="text-align: right;">Sample weight</th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Columbia River at Large</td>
<td style="text-align: left;">Pinot Gris</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">South Willamette Valley</td>
<td style="text-align: left;">Merlot</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rogue Valley</td>
<td style="text-align: left;">Pinot Blanc</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Willamette Valley</td>
<td style="text-align: left;">Pinot Blanc</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Umpqua</td>
<td style="text-align: left;">Pinot Gris</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia River at Large</td>
<td style="text-align: left;">Gewurztraminer</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">1.19</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Columbia River at Large</td>
<td style="text-align: left;">Merlot</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Umpqua</td>
<td style="text-align: left;">Merlot</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rogue Valley</td>
<td style="text-align: left;">Merlot</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">1.14</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Umpqua</td>
<td style="text-align: left;">Cabernet Savignon</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">1.06</td>
<td style="text-align: left;">Most up-weighted (thinnest groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Willamette Valley</td>
<td style="text-align: left;">Pinot Noir</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: left;">Least up-weighted (best-sampled groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Willamette Valley</td>
<td style="text-align: left;">Gewurztraminer</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: left;">Least up-weighted (best-sampled groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">North Willamette Valley</td>
<td style="text-align: left;">Chardonnay</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: left;">Least up-weighted (best-sampled groups)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia River at Large</td>
<td style="text-align: left;">Riesling/White Riesling</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: left;">Least up-weighted (best-sampled groups)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Umpqua</td>
<td style="text-align: left;">Riesling/White Riesling</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: left;">Least up-weighted (best-sampled groups)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="fitting-three-models-to-represent-a-sequential-growing-season" class="level2">
<h2 class="anchored" data-anchor-id="fitting-three-models-to-represent-a-sequential-growing-season">Fitting three models to represent a sequential growing season</h2>
<p>To capture the compounding effect of time and climate information, we fit three separate models, each representing what a grower would actually know at that point in the season: a spring model (frost risk only), a summer model (adding growing degree days, heat stress, and vapor pressure deficit), and a harvest model (adding veraison-to-harvest GDD, October precipitation, and ripening diurnal range).</p>
<p>All three stages were evaluated on the same time-blocked pre-2020 train/test partition rather than a simple random split. Oregon’s yield has trended upward over the study period, and its climate is itself autocorrelated from one year to the next, so a random split risks placing a test year directly adjacent to a training year from the same short-term trend, letting the model interpolate between nearby years rather than genuinely predicting an unseen one. To guard against this, we split pre-2020 data into contiguous three-year blocks, assigned roughly 10% of rows to test blocks spread across the full date range, and removed a one-year buffer from training on each side of the test block, so that no training year sits immediately adjacent to a test year. All three growing-season stages were tuned and evaluated on this same partition, so that any difference in performance across stages reflects the additional climate information available at that stage, not a different sample of years.</p>
<p>Post-2020 data was held out entirely from training and evaluated separately, as a case study rather than a fourth fold. We treat 2020 onward this way throughout the report because the wildfire smoke taint that disrupted that year’s harvest was a discrete event rather than part of the underlying gradual climate trend our models are built to capture; folding it into training on equal footing with other years would risk attributing a smoke-driven production loss to ordinary climate variability.</p>
<p>For a baseline metric against the SVM’s performance, we ran a weighted least squares linear model along the same sample splits. If the linear model found a relationship the SVM did not, that would point to the SVM being poorly suited to this data, rather than the underlying relationship being genuinely weak. Conversely, if the SVM detected a relationship the linear model could not, that would suggest a non-linear climate-yield relationship the RBF kernel is able to capture but a linear model cannot.</p>
</section>
<section id="climate-becomes-predictive-mid-season-then-declines" class="level2">
<h2 class="anchored" data-anchor-id="climate-becomes-predictive-mid-season-then-declines">Climate becomes predictive mid-season, then declines</h2>
<div class="cell" data-tbl-cap="Table 3: Held-out test performance by growing-season stage (SVM)">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 3: Held-out test performance by growing-season stage (SVM)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">R²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Stage 1: Spring</td>
<td style="text-align: right;">1.139</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stage 2: Summer</td>
<td style="text-align: right;">1.105</td>
<td style="text-align: right;">0.069</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stage 3: Harvest</td>
<td style="text-align: right;">1.123</td>
<td style="text-align: right;">0.040</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/residual-distribution-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure 9: Distribution of held-out residuals by growing-season stage"><img src="capstone_files/figure-html/residual-distribution-1.png" class="img-fluid figure-img" width="672" alt="Figure 9: Distribution of held-out residuals by growing-season stage"></a></p>
<figcaption>Figure 9: Distribution of held-out residuals by growing-season stage</figcaption>
</figure>
</div>
</div>
</div>
<p>Table 3 and Figure 9 show held-out test performance for all three growing-season stages. The relationship between climate and yield is modest throughout, an R² range of roughly 0.01 to 0.07. The staged models show that climate information is not predictive in the spring, becomes predictive in the summer, and then declines in predictive power once harvest-stage features are added. This pattern aligns with our correlation analysis, which found that growing degree days and heat stress were the most strongly correlated climate features with yield, while veraison-to-harvest GDD, October precipitation, and ripening diurnal range were not strongly correlated with yield.</p>
<p>Figure 9 shows a tighter spread of residuals for the summer model than for the harvest model, despite the harvest model having strictly more information available to it, suggesting that the harvest-stage features are not adding predictive value and may even be introducing noise into the model. Because of this, we use the summer model, not the full-season harvest model, as our final model for the post-2020 case study below.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/residuals-by-variety-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure 10: Residual spread by variety, across growing-season stages"><img src="capstone_files/figure-html/residuals-by-variety-1.png" class="img-fluid figure-img" width="672" alt="Figure 10: Residual spread by variety, across growing-season stages"></a></p>
<figcaption>Figure 10: Residual spread by variety, across growing-season stages</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 10 breaks down the same residuals by variety instead of by stage. As shown, the model is best-behaved for Oregon’s most heavily represented varieties: Pinot Noir and Chardonnay in particular show residuals centered close to zero across all three stages, while the state’s thinner varieties show wider, more biased spreads that do not meaningfully improve as later-stage features are added. This behavior becomes more explicit once we look at which features are contributing the most predictive power in the model. Ultimately, when climate information alone cannot fully explain a variety’s yield, the model falls back on variety identity itself as its best available predictor.</p>
</section>
<section id="model-reliance-on-variety-identity-vs.-climate-features" class="level2">
<h2 class="anchored" data-anchor-id="model-reliance-on-variety-identity-vs.-climate-features">Model reliance on variety identity vs.&nbsp;climate features</h2>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/importance-plot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure 11: Top 5 permutation-importance features by stage"><img src="capstone_files/figure-html/importance-plot-1.png" class="img-fluid figure-img" width="672" alt="Figure 11: Top 5 permutation-importance features by stage"></a></p>
<figcaption>Figure 11: Top 5 permutation-importance features by stage</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 11 shows why the residual patterns in Figure 10 look the way they do. In the spring model, variety identity dominates by a wide margin, consistent with the only available features at that point, frost risk and coldest spring night, showing no meaningful correlation with yield in our statistical analysis. With no useful climate signal to draw on, the model falls back on variety as its primary basis for prediction.</p>
<p>Variety identity remains the most important feature in the summer model as well, but growing degree days now emerges as a substantial contributor alongside it. This lines up directly with Table 3: the summer model’s jump in R² is attributable specifically to GDD becoming informative once it enters the feature set, not to any change in how much the model relies on variety. Harvest-stage features move both of these numbers in the same direction: model accuracy declines, and so does the model’s reliance on variety identity, without any harvest-specific feature stepping in to explain what’s lost. Rather than adding predictive signal, these features appear to dilute it, weakening the model’s focus on the one feature that had been driving its predictions all along.</p>
</section>
<section id="does-the-post-2020-period-leave-a-more-visible-mark-on-some-varieties" class="level2">
<h2 class="anchored" data-anchor-id="does-the-post-2020-period-leave-a-more-visible-mark-on-some-varieties">Does the post-2020 period leave a more visible mark on some varieties?</h2>
<p>Treating 2020 as a discrete disruption rather than part of the underlying climate trend, we can evaluate how well the summer model explains each variety’s yield from 2020 through 2024. We refit the summer model, the best-performing stage, on all pre-2020 data and evaluated it against each variety’s actual yield from 2020 through 2024. A wide or biased residual here does not mean climate hit that variety harder; the summer model has no wildfire or smoke-taint feature at all, so a large residual only tells us climate and variety together fail to explain that variety’s post-2020 yield, for reasons the model cannot see.</p>
<div class="cell" data-tbl-cap="Table 4: Post-2020 residuals by variety (summer model), 2020-2024">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 4: Post-2020 residuals by variety (summer model), 2020-2024</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 19%">
<col style="width: 20%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variety</th>
<th style="text-align: right;">Mean residual</th>
<th style="text-align: right;">SD of residual</th>
<th style="text-align: right;">N (2020-2024 rows)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pinot Blanc</td>
<td style="text-align: right;">-0.28</td>
<td style="text-align: right;">1.39</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Riesling/White Riesling</td>
<td style="text-align: right;">-0.23</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gewurztraminer</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chardonnay</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cabernet Savignon</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pinot Gris</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pinot Noir</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Merlot</td>
<td style="text-align: right;">-0.07</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">15</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/post2020-case-study-plot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure 12: Post-2020 residuals by variety, mean ± 1 SD (summer model)"><img src="capstone_files/figure-html/post2020-case-study-plot-1.png" class="img-fluid figure-img" width="672" alt="Figure 12: Post-2020 residuals by variety, mean ± 1 SD (summer model)"></a></p>
<figcaption>Figure 12: Post-2020 residuals by variety, mean ± 1 SD (summer model)</figcaption>
</figure>
</div>
</div>
</div>
<p>Table 4 and Figure 12 show that post-2020 unpredictability is not evenly spread across varieties, and it does not fall where our earlier smoke-taint finding might suggest. Pinot Blanc and Riesling show the widest residual spread and the most negative mean, meaning their yield is consistently lower than the model predicts, while Merlot shows the tightest residual spread and a mean near zero. Pinot Blanc’s result, drawn from only 10 rows, is the thinnest sample in this case study and should be read with particular caution.</p>
<p>Pinot Noir, the variety our production-weighted yield analysis showed took the sharpest single-year hit from 2020 wildfire smoke, tells a different story once the window widens to include the recovery years. Its residual spread is the second-tightest of any variety, and its mean residual is solidly positive, meaning actual yield from 2020 through 2024 ran above what climate alone would have predicted. Our framing of 2020 as a discrete, one-year disruption holds up once the window widens, not just for that single year: across the full post-2020 period, Pinot Noir’s climate-yield relationship looks stable, and the industry’s documented rebound (Figure 6) shows up here as a model that continues to underestimate, not overestimate, the variety’s recovery.</p>
<p>Since our summer model was never built to detect wildfire smoke specifically, we read Pinot Blanc and Riesling’s post-2020 unpredictability as a starting point for further investigation rather than a settled explanation. Whether it reflects a genuine variety-specific climate response, the compounding effect of multiple fire years our features do not capture, or simply the smaller and noisier samples these two varieties carry throughout this analysis, is a question this dataset alone cannot resolve.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Our original research question asked how climate has affected wine production in Oregon’s growing regions, and how that relationship has evolved since 1987. Our statistical and machine learning findings reveal that climate has changed Oregon’s growing conditions measurably, but it’s effect on wine depends heavily on which outcome, and which variety is being considered.</p>
<p>The climate trend itself is unambiguous. Growing degree days, peak summer temperature, and heat stress days have all risen over the past four decades, while the ripening-season diurnal temperature range, the day-night swing that gave Oregon’s Willamette Valley its Burgundy-like suitability for Pinot Noir in the first place, has quietly narrowed. Yield, however, has not shown the damage that trend alone might suggest. Statewide production-weighted yield has climbed for decades, our correlation analysis found warmer conditions generally corresponding to higher yield rather than lower, and our staged SVM model could explain at most 6.9% of yield’s variance from climate and variety alone, at its single best-performing stage. That is independent, held-out confirmation that climate is not yet the dominant force behind Oregon’s yield outcomes.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="capstone_files/figure-html/stacked-production-diurnal-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure 13: Statewide production-weighted yield and ripening-season diurnal temperature range, 1981–2024"><img src="capstone_files/figure-html/stacked-production-diurnal-1.png" class="img-fluid figure-img" width="672" alt="Figure 13: Statewide production-weighted yield and ripening-season diurnal temperature range, 1981–2024"></a></p>
<figcaption>Figure 13: Statewide production-weighted yield and ripening-season diurnal temperature range, 1981–2024</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 13 highlights the quality concern we identified earlier. The metric the industry measures and reports every year, yield, has moved in one direction. The metric that actually explains why Oregon built its reputation on Pinot Noir in the first place has moved in the other, causing a tightening of the diurnal temperature range. This is a quality concern that has yet to appear anywhere in Oregon’s production statistics. Our machine learning results reinforce just how real that separation is: ripening diurnal range did not rank among the top five most important features for predicting yield at any stage of the growing season, including the harvest-stage model where it was directly available to the model as a feature. A grower, or a researcher, looking at yield alone has no reason to suspect anything has changed.</p>
<p>That resilience is also not evenly distributed across varieties, our machine learning results showed that when climate information was thin the model fell back almost entirely on which variety it was predicting rather than on climate itself. This is direct evidence that variety identity, not climate, is the first-order determinant of yield outcomes at this stage of Oregon’s warming. Once summer climate features entered, growing degree days emerged as a significant second contributor alongside variety, but variety identity remained the single most important feature at every stage we tested, spring, summer, and harvest alike. And the residual diagnostics showed that the varieties the model struggles to characterize, Cabernet Sauvignon, Merlot, and Pinot Blanc in particular, are disproportionately the state’s minor plantings. We have the least reliable climate-sensitivity evidence for exactly the varieties with the smallest foothold to begin with, and the thinnest historical record to learn from.</p>
<p>Our post-2020 case study aligns with our earlier findings while also complicating them. If weather were leaving a uniform mark across varieties, we would expect the variety our earlier analysis flagged as hit hardest by 2020 wildfire smoke, Pinot Noir, to also be the hardest for a climate model to explain across the recovery years that followed. It is not. Once the window widens to 2020 through 2024, Pinot Noir’s yield is among the best-explained of any variety, and consistently better than a climate-only model would predict, showing a genuine recovery rather than a lingering instability. The varieties our summer model struggles with most across this same period, Pinot Blanc and Riesling, are not the ones the smoke-taint story would have predicted, and Pinot Blanc’s result rests on a sample too thin to weigh heavily on its own. Weather does appear to leave a more visible mark on some varieties than others, but not necessarily the ones a single dramatic year would lead us to expect, and not always for reasons a climate-and-variety model alone can identify.</p>
<p>This same climate shift also coincided with a real industry response: a consolidation around Pinot Noir, with Chardonnay and Riesling’s statewide shares declining over the same period. Pinot Noir shows a moderate positive yield relationship with heat accumulation in our data, comparable to Pinot Gris and stronger than several other varieties, so nothing in our yield findings suggests this consolidation has come at a yield cost. But the diurnal-range finding is the one piece of evidence in this entire report that has not yet shown up in a production number, a leading indicator for a wine-quality risk that a yield-only model, ours included, is structurally unable to see.</p>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<p>Several limitations shape how far these findings should be read. Our usable machine learning sample, roughly 1,000 region-by-variety-year observations after filtering, is small enough that individual thin varieties carry real uncertainty even after correcting for class imbalance through inverse-frequency sample weighting; we verified this weighting scheme against the alternative of synthetic oversampling (SMOTE) and found it produced more consistent train and test distributions for this dataset. An R² below 0.07 at every stage means our model should be read as evidence about where and for which varieties climate signal is present in the yield record, not as a production-forecasting tool. Umpqua’s yield pattern, flat and among the lowest of any region despite being the third-warmest by growing degree days, remains unexplained by the climate variables in our dataset and is flagged rather than resolved. Because yield was our only modeled outcome, these results say nothing directly about price or the qualitative characteristics that matter most to Oregon’s fine wine reputation, a limitation that reflects our finding that harvest-window features added no predictive value for yield specifically.</p>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">Future work</h2>
<p>The honest answer to our original research question is that Oregon’s climate-wine relationship has evolved in a way that is currently invisible in the production data, and will most plausibly first appear in the fruit quality of the state’s most heat-sensitive, most heavily planted variety. That is precisely the risk this project’s founding motivation, building a public, climate-linked Oregon wine dataset where none currently exists, was designed to help detect. It is also where we would point future work: extending this model to a quality proxy, such as price premium or critic-score data, rather than yield alone, disaggregating the thin varieties our current sample cannot yet characterize with confidence as more years of data accumulate, and extending the comparison to California and Washington that our original proposal envisioned but our first-phase data constraints did not allow.</p>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-frontiers2025bunchheating" class="csl-entry" role="listitem">
<span class="nocase">Bennett, Jeffrey S. et al.</span> 2025. <span>“Effects of Bunch Heating on Pinot Noir Grape Ripening: Changes in Berry Anthocyanin and Malic Acid Concentrations and Their Regulation.”</span> <em>Frontiers in Plant Physiology</em>. <a href="https://www.frontiersin.org/journals/plant-physiology/articles/10.3389/fphgy.2025.1701827/abstract">https://www.frontiersin.org/journals/plant-physiology/articles/10.3389/fphgy.2025.1701827/abstract</a>.
</div>
<div id="ref-cohen2012jexpbot" class="csl-entry" role="listitem">
Cohen, Sarah D., Julie M. Tarara, Gregory A. Gambetta, Mark A. Matthews, and James A. Kennedy. 2012. <span>“Impact of Diurnal Temperature Variation on Grape Berry Development, Proanthocyanidin Accumulation, and the Expression of Flavonoid Pathway Genes.”</span> <em>Journal of Experimental Botany</em> 63 (7): 2655–65. <a href="https://doi.org/10.1093/jxb/err449">https://doi.org/10.1093/jxb/err449</a>.
</div>
<div id="ref-ajev2012dtr" class="csl-entry" role="listitem">
Cohen, Seth D., Julie M. Tarara, and James A. Kennedy. 2012. <span>“Diurnal Temperature Range Compression Hastens Berry Development and Modifies Flavonoid Partitioning in Grapes.”</span> <em>American Journal of Enology and Viticulture</em> 63 (1): 112–26. <a href="https://www.ajevonline.org/content/63/1/112">https://www.ajevonline.org/content/63/1/112</a>.
</div>
<div id="ref-ucs2022nights" class="csl-entry" role="listitem">
Dahl, Kristina. 2022. <em>With Climate Change, Nights Are Warming Faster Than Days. Why?</em> Union of Concerned Scientists Blog. <a href="https://blog.ucs.org/kristy-dahl/with-climate-change-nights-are-warming-faster-than-days-why/">https://blog.ucs.org/kristy-dahl/with-climate-change-nights-are-warming-faster-than-days-why/</a>.
</div>
<div id="ref-delelee2025" class="csl-entry" role="listitem">
Delelee, L. M., A. J. Woodill, and P. A. Skinkis. 2025. <span>“Climate Change Projections Indicate Shifts in Phenology for Willamette Valley Pinot Noir.”</span> <em>American Journal of Enology and Viticulture</em>.
</div>
<div id="ref-jones2005" class="csl-entry" role="listitem">
Jones, Gregory V. 2005. <span>“Climate Change in the Western United States Grape Growing Regions.”</span> <em>Acta Horticulturae</em>.
</div>
<div id="ref-jonesHellman2003" class="csl-entry" role="listitem">
Jones, Gregory V., and Edward Hellman. 2003. <span>“Site Assessment.”</span> In <em>Oregon Viticulture</em>, 5th ed., edited by Edward Hellman. Oregon State University Press.
</div>
<div id="ref-kliewer1972" class="csl-entry" role="listitem">
Kliewer, W. M., and R. E. Torres. 1972. <span>“Effect of Controlled Day and Night Temperatures on Grape Coloration.”</span> <em>American Journal of Enology and Viticulture</em> 23 (2): 71–77. <a href="https://www.ajevonline.org/content/23/2/71">https://www.ajevonline.org/content/23/2/71</a>.
</div>
<div id="ref-liu2024dtr" class="csl-entry" role="listitem">
<span class="nocase">Liu, X. et al.</span> 2024. <span>“Increased Asymmetric Warming Rates Between Daytime and Nighttime Temperatures over Global Land During Recent Decades.”</span> <em>Geophysical Research Letters</em>. <a href="https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2024GL112832">https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2024GL112832</a>.
</div>
<div id="ref-oregonwinecensus" class="csl-entry" role="listitem">
Oregon Wine Board. 2026. <em>Oregon Vineyard and Winery Census</em>. <a href="https://industry.oregonwine.org/research/oregon-vineyard-and-winery-report/">https://industry.oregonwine.org/research/oregon-vineyard-and-winery-report/</a>.
</div>
<div id="ref-oregonwine2025willamette" class="csl-entry" role="listitem">
Oregon Wine Board Trade Resources. 2025. <em>Willamette Valley</em>. <a href="https://trade.oregonwine.org/resources/willamette-valley/">https://trade.oregonwine.org/resources/willamette-valley/</a>.
</div>
<div id="ref-prism2026" class="csl-entry" role="listitem">
PRISM Climate Group, Oregon State University. 2026. <em>PRISM Climate Group</em>. <a href="https://www.prism.oregonstate.edu/">https://www.prism.oregonstate.edu/</a>.
</div>
<div id="ref-pmc2022highTemp" class="csl-entry" role="listitem">
Rosas, Inés de, Leonor Deis, Yésica Baldo, Juan B. Cavagnaro, and Pablo F. Cavagnaro. 2022. <span>“High Temperature Alters Anthocyanin Concentration and Composition in Grape Berries of Malbec, Merlot, and Pinot Noir in a Cultivar-Dependent Manner.”</span> <em>Plants</em>. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9003205/">https://pmc.ncbi.nlm.nih.gov/articles/PMC9003205/</a>.
</div>
<div id="ref-skahill2025" class="csl-entry" role="listitem">
Skahill, B., and B. Berenguer. 2025. <em>Temperature-Based Climate Projections of Pinot Noir Suitability in the Willamette Valley AVA</em>. Oregon Wine Symposium.
</div>
<div id="ref-sommselect2026" class="csl-entry" role="listitem">
SommSelect. 2026. <em>Willamette Valley Wine Guide – Pinot Noir &amp; Top AVAs</em>. <a href="https://sommselect.com/blogs/tasting-notes/willamette-valley-wine-guide-history-regions-and-top-wines">https://sommselect.com/blogs/tasting-notes/willamette-valley-wine-guide-history-regions-and-top-wines</a>.
</div>
<div id="ref-vanleeuwen2024" class="csl-entry" role="listitem">
<span class="nocase">Van Leeuwen, C. et al.</span> 2024. <span>“Climate Change Impacts and Adaptations of Wine Production.”</span> <em>Nature Reviews Earth &amp; Environment</em>.
</div>
<div id="ref-nass2011gap" class="csl-entry" role="listitem">
Wine Data Researcher. 2022. <em>The 2022 US Census of Agriculture: Insights for Wine Organizations and Associations</em>. <a href="https://winedataresearcher.com/the-2022-us-census-of-agriculture-insights-for-wine-organizations-and-associations/">https://winedataresearcher.com/the-2022-us-census-of-agriculture-insights-for-wine-organizations-and-associations/</a>.
</div>
<div id="ref-wineamerica2025" class="csl-entry" role="listitem">
WineAmerica. 2025. <em>Economic Impact Study 2025: Oregon Wine Industry</em>. <a href="https://wineamerica.org/economic-impact-study-2025/oregon-wine-industry-2025/">https://wineamerica.org/economic-impact-study-2025/oregon-wine-industry-2025/</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>